pipeline {
    agent {
        docker {
            image 'tomcat:8.0.20-jre8' // Use the Tomcat Docker image
            args '-p 8080:8080' // Expose port 8080 for Tomcat
        }
    }
    
    stages {
        stage('Clone Repository') {
            steps {
                sh 'git clone https://github.com/sumair-aslam09/pipelines.git' // Replace with your GitHub repository URL
            }
        }
        
        stage('Deploy to Tomcat') {
            steps {
                dir('your-repo/target') { // Enter the directory where the WAR file is located
                    sh 'cp java-web-app*.war /usr/local/tomcat/webapps/java-web-app.war'
                }
            }
        }
    }
}
