---
- name: Install Nginx on localhost
  hosts: localhost
  connection: local  # Use a local connection to run on localhost
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      become: yes

    - name: Start Nginx service
      service:
        name: nginx
        state: started
      become: yes